Upgrades BulkRAX to version 4.5.0
uclibs/ucrate pull request #1002
Opened 2022-09-08 15:32 UTC by scherztc

Fixes #issuenumber ; refs #issuenumber

Present short summary (50 characters or less)

More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.

Description can have multiple paragraphs and you can use code examples inside:

``` ruby
class PostsController
  def index
    respond_with Post.limit(10)
  end
end
```

Changes proposed in this pull request:
* 
* 
*

2022-10-28 15:06 UTC, crowesn commented on config/environments/development.rb
> +  config.active_job.queue_adapter = :sidekiq
I think this was changed for convenience during dev but it should probably be reverted.

2022-10-28 15:08 UTC, crowesn commented on spec/features/hyrax/collection_type_spec.rb
> +      skip do
Consider adding a note to this skip for future reference e.g.
```
skip 'problem encountered with :en locale prefix' do
   ...
end
```

2022-10-28 15:08 UTC, crowesn commented on spec/features/hyrax/dashboard/collection_spec.rb
> +  Capybara.current_driver = :selenium_chrome
Is this something we want to make permanent?

2022-10-28 15:09 UTC, crowesn requested changes
A few in-line comments.

2022-10-28 15:12 UTC, crowesn commented
oh also, do we need to add the env variables to the the production .env?

2022-11-01 18:16 UTC, scherztc commented on config/environments/development.rb
> +  config.active_job.queue_adapter = :sidekiq
I didn't see a env.production in our code base.

2022-11-01 18:16 UTC, scherztc commented on config/environments/development.rb
> +  config.active_job.queue_adapter = :sidekiq
> I think this was changed for convenience during dev but it should probably be reverted.

DONE.

2022-11-01 18:16 UTC, scherztc commented on spec/features/hyrax/collection_type_spec.rb
> +      skip do
DONE.

2022-11-01 18:16 UTC, scherztc commented
> oh also, do we need to add the env variables to the the production .env?

I didn't see a .env.production in our code base.

2022-11-01 18:35 UTC, crowesn commented on spec/features/hyrax/dashboard/collection_spec.rb
> +          skip do
@scherztc Can you remind me the details of these skips?

2022-11-02 14:28 UTC, scherztc commented on spec/features/hyrax/dashboard/collection_spec.rb
> +          skip do
@crowesn The skips are in place because we couldn't get the test environment to recognize our locale files.  We were getting the double en.en.hyrax.admin_set_defaults.  I haven't done any more research on why were getting that.

2022-11-02 19:29 UTC, crowesn approved these changes

2022-11-02 19:30 UTC, merged