Add Capistrano support
uclibs/ucrate pull request #765
Opened 2019-07-22 19:07 UTC by bsp3ars

Fixes #761

This commit allows us to use the Capistrano tool to do all of our deploys. The official documentation is in the ucrate wiki. The only change outside of deployment that this impacts is the clamav gem. Instead of the commented out line, it was put into a group called production, so when you do future bundles, you'll need to run `bundle install --without production`.

2019-08-28 19:33 UTC, hortongn requested changes
@bsp3ars Go ahead and make the tweaks I suggested in the review and then I will deploy and test again to see if all is well.  Thanks

2019-09-10 16:56 UTC, bsp3ars commented on script/start_qa.sh
> +ln -s /mnt/common/branding "$(dirname "$(dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" )" )/shared/public/branding" 2> /dev/null
This should be okay, but we need to check to make sure @hortongn

2019-09-10 17:20 UTC, bsp3ars commented
@hortongn The changes have been made, and this is ready for another review/test

2019-09-13 20:07 UTC, hortongn requested changes
@bsp3ars There's still a couple of issues with symlinks on QA.

There's no symlink of public/system/avatars to /mnt/common/avatars

There's no symlink of public/uploads to /mnt/common/scholar-public-uploads

It DID properly create the branding symlink, but not uploads or avatars

2019-09-20 20:36 UTC, hortongn requested changes
@bsp3ars That fixed the symlink issues with QA.  However, I tried a deploy to scholar-dev and got this failure:

```
03 cp /srv/apps/scholar_capistrano/static/scholar-dev.variables /srv/apps/scholar_capistrano/releases/20190920203243/.env.development.local 2> /dev/null
#<Thread:0x00007faaff3cb980@/Users/hortongn/.rvm/gems/ruby-2.5.3@ucrate/gems/sshkit-1.19.1/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from /Users/hortongn/.rvm/gems/ruby-2.5.3@ucrate/gems/sshkit-1.19.1/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/hortongn/.rvm/gems/ruby-2.5.3@ucrate/gems/sshkit-1.19.1/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as scholar@localhost: c
p /srv/apps/scholar_capistrano/static/scholar-dev.variables /srv/apps/scholar_capistrano/releases/20190920203243/.env.development.local 2> /dev/null exit status: 1 (SSHKit::Runner::ExecuteEr
ror)
cp /srv/apps/scholar_capistrano/static/scholar-dev.variables /srv/apps/scholar_capistrano/releases/20190920203243/.env.development.local 2> /dev/null stdout: Nothing written
cp /srv/apps/scholar_capistrano/static/scholar-dev.variables /srv/apps/scholar_capistrano/releases/20190920203243/.env.development.local 2> /dev/null stderr: Nothing written
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as scholar@localhost: cp /srv/apps/scholar_capistrano/static/scholar-dev.variables /srv/apps/scholar_capistrano/releases/2019092020324
3/.env.development.local 2> /dev/null exit status: 1
cp /srv/apps/scholar_capistrano/static/scholar-dev.variables /srv/apps/scholar_capistrano/releases/20190920203243/.env.development.local 2> /dev/null stdout: Nothing written
cp /srv/apps/scholar_capistrano/static/scholar-dev.variables /srv/apps/scholar_capistrano/releases/20190920203243/.env.development.local 2> /dev/null stderr: Nothing written


Caused by:
SSHKit::Command::Failed: cp /srv/apps/scholar_capistrano/static/scholar-dev.variables /srv/apps/scholar_capistrano/releases/20190920203243/.env.development.local 2> /dev/null exit status: 1
cp /srv/apps/scholar_capistrano/static/scholar-dev.variables /srv/apps/scholar_capistrano/releases/20190920203243/.env.development.local 2> /dev/null stdout: Nothing written
cp /srv/apps/scholar_capistrano/static/scholar-dev.variables /srv/apps/scholar_capistrano/releases/20190920203243/.env.development.local 2> /dev/null stderr: Nothing written
```

2019-09-24 15:13 UTC, bsp3ars commented
@hortongn I wasn't able to duplicate this specific issue, however I did need to change the branch in /config/deploy/dev.rb
After I did this, the deploy was fast and I did not have any issues.

2019-09-24 19:01 UTC, hortongn commented
Rats, I forgot to change the branch.  I changed it for qa, but not dev.  Sorry.  I'll try again.

2019-09-30 21:05 UTC, hortongn approved these changes
@bsp3ars Nice work.  I think we need to tweak some of the wiki documentation, but this is ready to merge.

2019-09-30 21:05 UTC, merged