WIP: Log Format and Tracing Changes
uclibs/ucrate pull request #924
Opened 2021-05-14 14:28 UTC by bhanutejags

Fixes #issuenumber ; refs #issuenumber

Come with a log format that is easy to parse(using CloudWatch expressions), these logs should also have the necessary context/metadata to categorise or group log lines based on HTTP request ID, on Client IP, on User ID etc.

Here is an example of method in `ApplicationController` which adds a the Current User's ID to the log as a tag and to the XRay Traces.
``` ruby
around_action :add_tracing_and_logging_metadata

  def add_tracing_and_logging_metadata
    XRay.recorder.current_segment.user = current_user.try(:id) || 0

    logger.tagged("CU: #{current_user.try(:id) || 'UnauthenticatedUser'}") do
      yield
    end
  end
```

Changes proposed in this pull request:
* Added a new Log tags, which add some necessary context to each line of log.
  * These include things like a HTTP request ID, Client IP etc.
* Added Current User ID to XRay Traces.

2021-05-24 00:12 UTC, hortongn requested changes
@bhanutejags Looks good so far!  I made one comment inline about using log level :info in production mode.  Also, be sure to run `bundle exec rubocop` to clean up some style issues.

Is it maybe useful to use something like `if defined? Xray` on the Xray lines so that we can turn off Xray completely by commenting out the aws-xray-sdk gem?

2021-05-24 00:12 UTC, hortongn commented on config/environments/production.rb
>    config.log_level = :debug
I suggest we set the production log level to :info

2021-06-16 14:36 UTC, hortongn commented
@bhanutejags Here's an example from the log on scholar-qa.uc.edu:
```
I, [2021-06-16T10:31:44.465206 #9343]  INFO -- : [4ef0da96-5c5f-4df1-9b41-c15e9ea5bb58] [1-60ca0b50-49951f742a6133fb7f8a8242] [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_1
5_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36] [scholar-qa] [10.11.157.241] [No-X-Forwarded-For-Header] [CU: 6]   Rendered /srv/apps/scho
lar_capistrano/shared/vendor/bundle/ruby/2.7.0/gems/hyrax-2.9.4/app/views/shared/_locale_picker.html.erb (0.2ms)
```

All looks good I think except every line is reporting `[No-X-Forwarded-For-Header]`.  Do we need to make a tweak to Apache to fix that?

2021-06-18 03:21 UTC, bhanutejags commented
> @bhanutejags Here's an example from the log on scholar-qa.uc.edu:
> 
> ```
> I, [2021-06-16T10:31:44.465206 #9343]  INFO -- : [4ef0da96-5c5f-4df1-9b41-c15e9ea5bb58] [1-60ca0b50-49951f742a6133fb7f8a8242] [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_1
> 5_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36] [scholar-qa] [10.11.157.241] [No-X-Forwarded-For-Header] [CU: 6]   Rendered /srv/apps/scho
> lar_capistrano/shared/vendor/bundle/ruby/2.7.0/gems/hyrax-2.9.4/app/views/shared/_locale_picker.html.erb (0.2ms)
> ```
> 
> All looks good I think except every line is reporting `[No-X-Forwarded-For-Header]`. Do we need to make a tweak to Apache to fix that?

Looks like that, but when I tested with a local Apache HTTP Server installation, it did not need any specific configuration beyond that of simple [VirtualHost](https://httpd.apache.org/docs/2.4/vhosts/examples.html).
I'll go over the Scholar QA's Apache HTTP Server Configuration.

2021-09-09 18:01 UTC, hortongn commented
Rebase, review, and merge this after xray has been re-added to project

2023-09-25 16:18 UTC, scherztc commented
We are going to close this PR, since we are no longer using Amazon tools like X-Ray for logging.

2023-09-25 16:18 UTC, closed without merging